### PR TITLE
Delegate monitor bug - Closes #948

### LINKED ISSUE #948: Active delegate is not appearing on DelegatesMonitor tab
### Expected behavior
The active delegate should appear on the `DelegateMonitor`
### Actual behavior
- The actove delegate doesn't appear on `DelegatesMonitor` tab
Here is the actual delegate who is forging, but doesn't appear on the explorer
http://devnet-seed-01.liskdev.net:4000/api/delegates
```
{
"username": "mamamia",
"voteWeight": "9977270596139138",
"rewards": "10500000000",
"producedBlocks": 22,
"missedBlocks": 4,
"productivity": 84.62,
"account": {
"address": "9666993061956402310L",
"publicKey": "89d1727c62e6c3562d046fd5e35573896daee2d643dc7a767ebdebd420511a98",
"secondPublicKey": ""
},
"approval": 99.72
}
```
http://devnet-seed-01.liskdev.net:6040/delegateMonitor
### Steps to reproduce
- Register a delegate
- Gain votes to be able to forge (101 slots)

### PR DESCRIPTION
**Pull request by MichalTuleja**
### What was the problem?
This PR resolves #948

### How was it solved?

- Updated the logic responsible for delegate updates

### How was it tested?

Manually on a local instance connected to devnet.

### CODE REVIEW

**Review by slaweet — CHANGES_REQUESTED** [review]
I'm not sure whether a new round starts on `currentHeight % 101 === 0` or `currentHeight % 101 === 1`.

I think a more clear approach would be to listen to `rounds/change` with
`socketClient.socket.on('rounds/change', refreshDelegatesAtRoundStart);` and then this condition is not needed at all. 

I would have done it previously with `rounds/change`, but I wasn't aware that it exists at that time.

**Comment by MichalTuleja** [comment]
I have checked it again, due to the first block that is equal to 1, not 0, the formula `(currentHeight - 1) % 101` gives zero on the beginning of each round. The block-based approach is correct but it causes a delay because the block has to be built before the round start is detected. 

The `rounds/change` event might be an answer but it was never tested for that purpose.

**Comment by MichalTuleja** [comment]
I've eventually implemented a solution based on the `rounds/change` event, seems to work correctly now.

**Review by slaweet — APPROVED** [review]
👍

**Pull request merged**
