### PR TITLE
remove broadhash and add port on peers monitoring page

### PR DESCRIPTION
**Pull request by Doweig**

### CODE REVIEW

**Comment by 4miners** [comment]
Yep, that line and parent `td` element also:
```
        <td class="hidden-xs hidden-sm hidden-md">
          <span class="text-muted ellipsis broadhash">{{p.broadhash}}</span>
        </td>
```

**Comment by Doweig** [comment]
Yes, my bad. All good now

**Comment by 4miners** [comment]
Thank you, please always check code in test environment before commit it. :)

**Comment by Doweig** [comment]
Yes, should have. I just copied that one from Ark, since we don't have a broadhash it didn't show anything on the front end

**Pull request merged**
