### PR TITLE
Fix css for retina display

### PR DESCRIPTION
**Pull request by alepop**
I found that I made a mistake in this PR https://github.com/LiskHQ/lisk-explorer/pull/156.

This PR fixes the URL path to logo image.

### CODE REVIEW

**Comment by Isabello** [comment]
@alepop please rebase this PR on the 1.2.0 branch.

**Comment by alepop** [comment]
@Isabello done

**Comment by Isabello** [comment]
Tests fail due to dev branch required changes. I will override this one as it has no impact on the tested items.

**Comment by Isabello** [comment]
@alepop thank you for your hard work.

**Pull request merged**
