### PR TITLE
Replace Zeroclipboard with Clipboardjs - Closes #228

### LINKED ISSUE #228: Copy buttons don't function
### Expected behaviour
From the address page, the pubkey or addres should copy to the clipboard when clicking the copy button

### Actual behaviour
From the address page, the copy buttons do not work

### Steps to reproduce
Navigate to: https://explorer.lisk.io/address/7621048351401864465L

Click the buttons to the right of the address or publickey. 

Try to paste.

### PR DESCRIPTION
**Pull request by alepop**
Closes #228

### CODE REVIEW

**Comment by alepop** [comment]
@4miners copy button is hidden on mobile

**Comment by Isabello** [comment]
Probably was hidden due to flash dependency on ZeroClipboard

**Comment by alepop** [comment]
@Isabello ok then i add it to mobile too

**Comment by alepop** [comment]
@4miners, @Isabello on a mobile device the tooltip is looking bad (in some blocks they cut by wrappers). Maybe the best way is to show the native alert window with a message about copy success?

**Comment by Isabello** [comment]
@alepop I am not sure to be honest. I think a native window might be best if it is not too intrusive to the user experience.

**Comment by 4miners** [comment]
@alepop There is still some left:
```
   app.js
     74 |        logger.info(data)
                                  ^ [W033] Missing semicolon.
   utils/logger.js
     25 |    var stringMsg = typeof msg === "string" ? msg : JSON.stringify(msg);
                                                    ^ [W109] Strings must use singlequote.
     26 |    var parsedMsg = stringMsg.replace(/(\r\n|\n|\r)/gm, " ");
                                                                    ^ [W109] Strings must use singlequote.
     29 |      var stringExtra = typeof extra === "string" ? extra : JSON.stringify(extra);
                                                          ^ [W109] Strings must use singlequote.
```

**Comment by alepop** [comment]
@slaweet my PR did not touch `app.js` or `utils` files.

**Comment by 4miners** [comment]
@alepop Yeah, sorry, wrong PR. :)

**Pull request merged**
